### ISSUE TITLE
Parse PDF to json

### ISSUE THREAD

**Issue by Mayar2009** [allenai/s2orc#1]
In your article you have mentioned that 
"
PDF to JSON We use GROBID5 (Lopez, 2009)
to process each PDF: (i) extract the paper’s Title6, Authors, Year, Venue and Abstract, (ii) extract paragraphs from the Body text organized under extracted Section headings, (iii) extract Figure and
Table captions, (iv) remove equations, table content, headers, and footers from the body text, (v)
extract in-line citations from the abstract and body text, (vi) extract and parse each bibliography entry, identifying its Title, Authors, Year, and Venue, and (vi) link the in-line citation mentions to their
corresponding bibliography entries. The resulting parses are expressed in JSON format as described
in Appendix E."

Is your parser open source code?
Can we use it?

**Comment by kyleclo** [comment]
Hey @Mayar2009  thanks for your interest in the project!  We'd be happy to share the parser code once we finish making some more changes / cleaning up the code.

**Comment by Mayar2009** [comment]
thanks! hope soon ! keep me please in the process!

**Comment by viveksck** [comment]
Hello @kyleclo, I also noticed that the value for the section field is pretty much empty in most of the Grob Parses (except for of course the abstract). It would be very useful to know if citation context is from the Introduction, Related Work or Methods sections.

I am also wondering if author affiliations could be added to the JSON.

**Comment by kyleclo** [comment]
Hey @viveksck  Thanks for catching that!  I agree that the section information is super important, and we've had several users express that they want that information.  Unfortunately I think this is an issue with GROBID parsing which isn't super accurate when it comes to section information.  I tried out ScienceParse, which is also similarly iffy with sections.

I'm currently in the process of looking into whether there's something that can be easily fixed within GROBID (or modified within our parser) that will capture Sections better.  In the meantime, if you happen to know of a PDF parsing tool that handles Sections better than GROBID/ScienceParse, I'd love to try running it through the pipeline.

Regarding author affiliations, they're in there, as can see from paper_id `140112606`:
```
{
  "title": "Development of a Cassava Starch Extraction Machine",
  "authors": [
    {
      "first": "L",
      "middle": [],
      "last": "Olutayo",
      "suffix": "",
      "affiliation": {
        "laboratory": "",
        "institution": "Rufus Giwa Polytechnic",
        "location": {
          "settlement": "Owo, Ondo-state",
          "country": "Nigeria"
        }
      },
      "email": ""
    },
```
But I also agree that they're sparse.  We didn't spend a lot of focus on making sure author affiliation was accurate (just author names), and it seems unlikely that will have time to get to it since the focus is more on quality of the body text (e.g. sections, citations, etc.)

**Comment by Mayar2009** [comment]
Besides using Grobid we could not parse references.
if you could help with that I will be grateful

**Comment by kyleclo** [comment]
@Mayar2009  could you explain what you mean by "could not parse references"?  I'm pretty sure GROBID outputs references, when it manages to detect them?

**Comment by Mayar2009** [comment]
yes I can see them in the tei file but seems I need a parser to convert the tei file to json file
I am asking about that

**Comment by kyleclo** [comment]
Hey @Mayar2009,  thanks for this request.  We've heard from others too that also want access to our TeiXML to JSON parser, so we're planning on releasing it.

**Comment by Mayar2009** [comment]
@kyleclo thanks!
